### ISSUE TITLE
Add support for short16 and float32 images

### ISSUE THREAD

**Issue by kmader** [DeepInfer/Slicer-DeepInfer#2]
Currently only uint8 images are supported (https://github.com/DeepInfer/Slicer-DeepInfer/blob/master/DeepInfer/DeepInfer.py#L642) which is very limiting for techniques like CT. It would be good to have support for short and floating point images based on the json files

**Comment by mpslxz** [comment]
@mehrtash What do you think?

**Comment by mehrtash** [comment]
@kmader @mpslxz definitely makes sense! There is no need to limit ourselves to a specific datatype at slicer level. We should move any preprocessing to the docker side.

**Comment by mehrtash** [comment]
@kmader This has been fixed. Now the original image will be sent to the docker for further processing. All conversions will be handled inside the docker.
